### ISSUE TITLE
Not Starting 

### ISSUE THREAD

**Issue by CroissantDuNord** [OceanCyanTech/CompInfo#1]
### Software Info
| Windows 11 22H2

When i start the program nothing start just loading

**Comment by OceanCyanTech** [comment]
Thank you for raising your issue.
Please follow these steps:
https://github.com/OceanCyanTech/CompInfo/wiki/Help.
If there is no Log File for the app, please try reinstalling the app or leave a comment here...

If your issue is solved, please comment here so that we can close this issue

**Comment by CroissantDuNord** [comment]
Hello so i made the log_en.txt in the file dir but nothing in the file
![image](https://user-images.githubusercontent.com/79372025/170862889-e3cd15e0-d8cf-4c29-8de8-b9d669ba43ff.png)

**Comment by OceanCyanTech** [comment]
Please open the Event Viewer app from the Start Menu and go to Windows Logs > Application
![image](https://user-images.githubusercontent.com/106421266/170866854-5e1f4c7e-f5e4-4348-9347-3b225cf57f3f.png)
Open CompInfo before opening Event Viewer

**Comment by CroissantDuNord** [comment]
Now i have logs
![image](https://user-images.githubusercontent.com/79372025/170870409-d296a9a2-3e59-40d8-9210-c02eff52edf9.png)

**Comment by OceanCyanTech** [comment]
Ok thanks for the info, I'm trying to work on this issue. This might take a day...

**Comment by OceanCyanTech** [comment]
@minecraft333238, This Issue has been fixed... Please download the setup file again and install it... If not please comment.
Discord Server: https://discord.gg/9emhaEh6s3

**Comment by OceanCyanTech** [comment]
Hello, there is no response @minecraft333238 regarding this issue. This issue will be closed as fixed or resolved if no response is there by 6th June.
